INSERT INTO ITEM (NAME, PRICE) VALUES ('Pen',5);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Book',10);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Bag',30);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Pencil',3);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Shoe',45);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Box',5);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Cap',25);